# -*- coding: utf-8 -*-

import names


def main():
    test.compare(waitForObjectExists(names.mainWindow_nameLabel_QLabel).geometry.x, 9)
    test.compare(waitForObjectExists(names.mainWindow_nameLabel_QLabel).geometry.y, 31)
    test.compare(waitForObjectExists(names.mainWindow_nameLabel_QLabel).geometry.width, 85)
    test.compare(waitForObjectExists(names.mainWindow_nameLabel_QLabel).geometry.height, 35)
    test.compare(waitForObjectExists(names.mainWindow_phoneLabel_QLabel).geometry.x, 9)
    test.compare(waitForObjectExists(names.mainWindow_phoneLabel_QLabel).geometry.y, 72)
    test.compare(waitForObjectExists(names.mainWindow_phoneLabel_QLabel).geometry.width, 85)
    test.compare(waitForObjectExists(names.mainWindow_phoneLabel_QLabel).geometry.height, 35)
    test.compare(waitForObjectExists(names.mainWindow_emailLabel_QLabel).geometry.x, 9)
    test.compare(waitForObjectExists(names.mainWindow_emailLabel_QLabel).geometry.y, 113)
    test.compare(waitForObjectExists(names.mainWindow_emailLabel_QLabel).geometry.width, 85)
    test.compare(waitForObjectExists(names.mainWindow_emailLabel_QLabel).geometry.height, 35)
    test.compare(waitForObjectExists(names.mainWindow_nameTxt_QPlainTextEdit).geometry.x, 100)
    test.compare(waitForObjectExists(names.mainWindow_nameTxt_QPlainTextEdit).geometry.y, 31)
    test.compare(waitForObjectExists(names.mainWindow_nameTxt_QPlainTextEdit).geometry.width, 316)
    test.compare(waitForObjectExists(names.mainWindow_nameTxt_QPlainTextEdit).geometry.height, 35)
    test.compare(waitForObjectExists(names.mainWindow_phoneTxt_QPlainTextEdit).geometry.x, 100)
    test.compare(waitForObjectExists(names.mainWindow_phoneTxt_QPlainTextEdit).geometry.y, 72)
    test.compare(waitForObjectExists(names.mainWindow_phoneTxt_QPlainTextEdit).geometry.width, 316)
    test.compare(waitForObjectExists(names.mainWindow_phoneTxt_QPlainTextEdit).geometry.height, 35)
    test.compare(waitForObjectExists(names.mainWindow_emailTxt_QPlainTextEdit).geometry.x, 100)
    test.compare(waitForObjectExists(names.mainWindow_emailTxt_QPlainTextEdit).geometry.y, 113)
    test.compare(waitForObjectExists(names.mainWindow_emailTxt_QPlainTextEdit).geometry.width, 316)
    test.compare(waitForObjectExists(names.mainWindow_emailTxt_QPlainTextEdit).geometry.height, 35)
    test.compare(waitForObjectExists(names.mainWindow_addBtn_QPushButton).geometry.x, 9)
    test.compare(waitForObjectExists(names.mainWindow_addBtn_QPushButton).geometry.y, 176)
    test.compare(waitForObjectExists(names.mainWindow_addBtn_QPushButton).geometry.width, 407)
    test.compare(waitForObjectExists(names.mainWindow_addBtn_QPushButton).geometry.height, 24)
    test.compare(waitForObjectExists(names.mainWindow_phoneBookTable_QTableWidget).geometry.x, 9)
    test.compare(waitForObjectExists(names.mainWindow_phoneBookTable_QTableWidget).geometry.y, 269)
    test.compare(waitForObjectExists(names.mainWindow_phoneBookTable_QTableWidget).geometry.width, 407)
    test.compare(waitForObjectExists(names.mainWindow_phoneBookTable_QTableWidget).geometry.height, 320)
    test.compare(waitForObjectExists(names.mainWindow_removeBtn_QPushButton).geometry.x, 9)
    test.compare(waitForObjectExists(names.mainWindow_removeBtn_QPushButton).geometry.y, 595)
    test.compare(waitForObjectExists(names.mainWindow_removeBtn_QPushButton).geometry.width, 407)
    test.compare(waitForObjectExists(names.mainWindow_removeBtn_QPushButton).geometry.height, 24)
